DROP TABLE IF EXISTS EVENT;
CREATE TABLE EVENT (
	EVENT_ID LONG NOT NULL,
	EVENT_NAME VARCHAR NOT NULL,
	EVENT_TYPE VARCHAR NOT NULL,
	CONSTRAINT EVENT_PK PRIMARY KEY(EVENT_ID)
);

DROP TABLE IF EXISTS MGM_EVENT;
CREATE TABLE MGM_EVENT (
	EVENT_ID LONG NOT NULL,
	DETAIL_NAME VARCHAR NOT NULL,
	MGM_TEL VARCHAR NOT NULL,
	CONSTRAINT MGM_PK PRIMARY KEY(EVENT_ID)
);

DROP TABLE IF EXISTS POST_EVENT;
CREATE TABLE POST_EVENT (
	EVENT_ID LONG NOT NULL,
	DETAIL_NAME VARCHAR NOT NULL,
	EMAIL VARCHAR NOT NULL,
	CONSTRAINT POST_PK PRIMARY KEY(EVENT_ID)
);

INSERT INTO EVENT(EVENT_ID, EVENT_NAME, EVENT_TYPE) VALUES(1, 'MGM EVENT1', 'MGM');
INSERT INTO EVENT(EVENT_ID, EVENT_NAME, EVENT_TYPE) VALUES(2, 'MGM EVENT2', 'MGM');
INSERT INTO EVENT(EVENT_ID, EVENT_NAME, EVENT_TYPE) VALUES(3, 'POST EVENT1', 'POST');
INSERT INTO EVENT(EVENT_ID, EVENT_NAME, EVENT_TYPE) VALUES(4, 'POST EVENT2', 'POST');

INSERT INTO MGM_EVENT(EVENT_ID, DETAIL_NAME, MGM_TEL) VALUES(1, 'BIG MGM EVENT!!!', '010-1234-5678');
INSERT INTO MGM_EVENT(EVENT_ID, DETAIL_NAME, MGM_TEL) VALUES(2, 'SURPRISE MGM EVENT!!!', '010-9876-5432');

INSERT INTO POST_EVENT(EVENT_ID, DETAIL_NAME, EMAIL) VALUES(3, 'BIG POST EVENT!!!', 'test1@test.com');
INSERT INTO POST_EVENT(EVENT_ID, DETAIL_NAME, EMAIL) VALUES(4, 'SURPISE POST EVENT!!!', 'test2@test.com');